@startuml

activate Order

Order -> Payment: AuthorizePayment
activate Payment

Order <-- Payment: OK
deactivate Payment

Order -> Warehouse: ReserveItems
activate Warehouse

Order <-- Warehouse: OK
deactivate Warehouse

Order -> Delivery: ScheduleDelivery
activate Delivery

Order <-- Delivery: OK
deactivate Delivery

Order -> Payment: CompletePayment
activate Payment

alt #lightgreen Успешное подтверждение платежа

Order <-- Payment: OK

else #lightpink Откат операций

Order <-- Payment: ERROR
deactivate Payment

Order -> Delivery: CancelSchedule
activate Delivery

Order <-- Delivery: OK
deactivate Delivery

Order -> Warehouse: RemoveItemsReservation
activate Warehouse

Order <-- Warehouse: OK
deactivate Warehouse

Order -> Payment: CancelPayment\n(в случае отклонения платежа\n делать ничего не нужно)
activate Payment

Order <-- Payment: OK
deactivate Payment
deactivate Order

end

@enduml