@startuml

activate Order

Order -> Payment: AuthorizePayment
activate Payment

Order <-- Payment: OK
deactivate Payment

Order -> Warehouse: ReserveItems
activate Warehouse

Order <-- Warehouse: OK
deactivate Warehouse

Order -> Delivery: ScheduleDelivery
activate Delivery

Order <-- Delivery: OK
deactivate Delivery

Order -> Payment: CompletePayment
activate Payment

alt #lightgreen Успешное подтверждение платежа\n(Последний этап саги проведения платежа)

Order <-- Payment: OK

Order -> Delivery: ProcessDelivery
activate Delivery

Delivery -> Delivery: Сборка зарезервированного товара\nОтправка заказа

Delivery -> Order: OrderDelivered
deactivate Delivery

else #lightpink Не удалось завершить платеж\n(Откат всех предыдущих операций)

Order <-- Payment: ERROR
deactivate Payment

Order -> Delivery: CancelSchedule
activate Delivery

Order <-- Delivery: OK
deactivate Delivery

Order -> Warehouse: RemoveItemsReservation
activate Warehouse

Order <-- Warehouse: OK
deactivate Warehouse

Order -> Payment: CancelPayment\n(в случае отклонения платежа\n делать ничего не нужно)
activate Payment

Order <-- Payment: OK
deactivate Payment
deactivate Order

end

@enduml