@startuml
skinparam defaultTextAlignment center

actor User [
    Frontend
]

cloud APIGateway [
    Api Gateway
    (Traefik)
]

component Auth

component Cart

component Order

component Catalog

component Payment

component Warehouse

component Delivery

User -right-> APIGateway

APIGateway -right-> Auth: GET /auth
APIGateway <.right. Auth: X-Auth-User-ID: ...

APIGateway --> Catalog: GET /products

APIGateway --> Cart: PUT /cart\nPOST /checkout

Cart --> Catalog: GET /products

Cart ---> Order: PUT /orders

Order ---> Payment: PUT /payments\nPOST /payment/{orderID}/complete\nPOST /payment/{orderID}/cancel

Order ---> Warehouse: POST /warehouse/order/{orderID}/reserve\nDELETE /warehouse/order/{orderID}/reserve

Order --->  Delivery: POST /delivery/{orderID}/schedule\nDELETE /delivery/{orderID}/schedule

@enduml